### ISSUE TITLE
Request to expose "preSelectItemOnMultipleSelection" paramater

### ISSUE THREAD

**Issue by emeisinga** [hansemannn/titanium-imagepicker#14]
The module now standard selects the first image in the gallery, this is not desirable by me.

**Comment by m1ga** [comment]
+1 for exposing that as a parameter.
Having trouble building it myself otherwise I would try it :)

**Comment by hansemannn** [comment]
It's actually exposed already, but I haven't pushed, yet. Will do now!

**Comment by hansemannn** [comment]
See https://github.com/hansemannn/titanium-imagepicker/releases/tag/ios-5.0.0
