### ISSUE TITLE
iPad simulator can not choose pictures

### ISSUE THREAD

**Issue by caspahouzer** [hansemannn/titanium-imagepicker#7]
When I start the picker with this parameter, I can not choose any images

```
maxImageSelection: 10,
        tintColor: Alloy.CFG.color.main,
        doneButtonTitle: L('done'),
        nextButtonTitle: L('forward'),
        cancelButtonTitle: L('cancel'),
        cameraTitle: L('camera'),
        libraryTitle: L('gallery'),
        albumsTitle: L('albums'),
        title: L('choose_images'),
```

![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-08-20 at 09 54 29](https://user-images.githubusercontent.com/1126641/90732615-a6a08e80-e2cb-11ea-8613-57c4b75a1977.png)

Working with 9.0.3.GA on 13.6 iPad simulator. iPhone simulator works as expected btw

**Comment by hansemannn** [comment]
It seems to be an issue with the native YPImagePicker library and can be fixed by setting the content-size when using an iPad. Can you perform that change? It is described here (one property): https://github.com/Yummypets/YPImagePicker#default-configuration

**Comment by hansemannn** [comment]
I just published https://github.com/hansemannn/titanium-imagepicker/releases/tag/ios-3.1.0 which should fix this! Can you confirm?

**Comment by caspahouzer** [comment]
Yes, that works. Thank you.

But when it opens, the first image is zoomed to fill out the preview. Can I prevent that with any parameter?

https://share.getcloudapp.com/NQuro0G2

**Comment by hansemannn** [comment]
Okay, thats another question. I'll close this one. You can find the docs of the library [here](https://github.com/Yummypets/YPImagePicker#general) and play with it
