### ISSUE TITLE
While running android module 3.0.0 Application Installer abnormal process termination. Process exit value was 1

### ISSUE THREAD

**Issue by moizchhatriwala** [hansemannn/titanium-imagepicker#8]
Hello,
Thanks for getting new android module release, but while compiling the project application getting following issue:

[ERROR] :  [GRADLE] FAILURE: Build failed with an exception.
[ERROR] :  [GRADLE] 
[ERROR] :  [GRADLE] * What went wrong:
[ERROR] :  [GRADLE] Execution failed for task ':app:mergeDebugResources'.
[ERROR] :  [GRADLE] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[ERROR] :  [GRADLE]    > Could not find com.github.lwj1994:Matisse:0.5.3-4.
[ERROR] :  [GRADLE]      Searched in the following locations:
[ERROR] :  [GRADLE]        - https://dl.google.com/dl/android/maven2/com/github/lwj1994/Matisse/0.5.3-4/Matisse-0.5.3-4.pom
[ERROR] :  [GRADLE]        - https://jcenter.bintray.com/com/github/lwj1994/Matisse/0.5.3-4/Matisse-0.5.3-4.pom
[ERROR] :  [GRADLE]        - file:/Users/moizchhatriwala/Library/Application Support/Titanium/mobilesdk/osx/9.3.2.GA/android/m2repository/com/github/lwj1994/Matisse/0.5.3-4/Matisse-0.5.3-4.pom
[ERROR] :  [GRADLE]        - file:/Users/moizchhatriwala/Documents/Appcelerator_Studio_Workspace1/Siportal/modules/android/ti.identity/3.0.2/m2repository/com/github/lwj1994/Matisse/0.5.3-4/Matisse-0.5.3-4.pom
[ERROR] :  [GRADLE]        - file:/Users/moizchhatriwala/Documents/Appcelerator_Studio_Workspace1/Siportal/modules/android/ti.imagepicker/3.0.0/m2repository/com/github/lwj1994/Matisse/0.5.3-4/Matisse-0.5.3-4.pom
[ERROR] :  [GRADLE]      Required by:
[ERROR] :  [GRADLE]          project :app > ti:imagepicker:3.0.0
[ERROR] :  [GRADLE] 
[ERROR] :  [GRADLE] * Try:
[ERROR] :  [GRADLE] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[ERROR] :  [GRADLE] 
[ERROR] :  [GRADLE] * Get more help at https://help.gradle.org
[ERROR] :  [GRADLE] 
[ERROR] :  [GRADLE] BUILD FAILED in 2s
[ERROR] :  "gradlew" tool returned exit code: 1
[ERROR] Application Installer abnormal process termination. Process exit value was 1

I am using titanium sdk 9.3.0 to run the project.

**Comment by hansemannn** [comment]
You have to have the maven-jitpack repo in your app-wide build.gradle (in app/platform/android/build.gradle):
```
repositories {
	maven { url 'https://jitpack.io' }
}
```

I will update the readme accordingly!

**Comment by moizchhatriwala** [comment]
Hello,
I have tried to used the module directly in project, but I got the errors which I shared with you above. I also tried to build the module with the source code but build.gradle unable to find this:   implementation 'com.github.lwj1994:Matisse:0.5.3-4'

Any help will be greatly appreciated.

Thanks.

**Comment by hansemannn** [comment]
Then I can't help, sorry.

**Comment by moizchhatriwala** [comment]
Did you ever run this module on your machine, if you can share the build.gradle with me that to use for module compilation or if you can let us know what all library are added in this module, I can add them here

**Comment by moizchhatriwala** [comment]
I tried changing the build.gradle to this:


repositories {
    jcenter()
    mavenCentral()
}

dependencies {
	implementation group: 'com.zhihu.android', name: 'matisse', version: '0.5.3-beta3'
	implementation group: 'com.github.bumptech.glide', name: 'glide', version: '4.1.1'
	
}

So now module compiled for me, but when I run app it give me this error while opening the picker:

[ERROR] :  TiExceptionHandler: (main) [20101,22865] No virtual method override(II)Lcom/bumptech/glide/request/BaseRequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/~~6MEZC-F50uo221z-g42VOA==/com.siportal.mobileapp-GsjKh8OgLR7-QhnpXk0hpA==/base.apk!classes2.dex)
[ERROR] :  TiExceptionHandler:
[ERROR] :  TiExceptionHandler:     com.zhihu.matisse.engine.impl.GlideEngine.loadThumbnail(GlideEngine.java:40)
[ERROR] :  TiExceptionHandler:     com.zhihu.matisse.internal.ui.widget.MediaGrid.setImage(MediaGrid.java:117)
[ERROR] :  TiExceptionHandler:     com.zhihu.matisse.internal.ui.widget.MediaGrid.bindMedia(MediaGrid.java:84)
[ERROR] :  TiExceptionHandler:     com.zhihu.matisse.internal.ui.adapter.AlbumMediaAdapter.onBindViewHolder(AlbumMediaAdapter.java:122)
[ERROR] :  TiExceptionHandler:     com.zhihu.matisse.internal.ui.adapter.RecyclerViewCursorAdapter.onBindViewHolder(RecyclerViewCursorAdapter.java:45)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
[ERROR] :  TiExceptionHandler:     androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
[ERROR] :  TiExceptionHandler:     android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
[ERROR] :  TiExceptionHandler:     android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
[ERROR] :  TiExceptionHandler:     android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
[ERROR] :  TiExceptionHandler:     android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
[ERROR] :  TiExceptionHandler:     android.widget.FrameLayout.onLayout(FrameLayout.java:270)
[ERROR] :  TiExceptionHandler:     com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
[ERROR] :  TiExceptionHandler:     android.view.View.layout(View.java:22844)
[ERROR] :  TiExceptionHandler:     android.view.ViewGroup.layout(ViewGroup.java:6389)
[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3470)
[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2938)
[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
[ERROR] :  TiExceptionHandler:     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
[ERROR] :  TiExceptionHandler:     android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
[ERROR] :  TiExceptionHandler:     android.view.Choreographer.doCallbacks(Choreographer.java:796)
[ERROR] :  TiExceptionHandler:     android.view.Choreographer.doFrame(Choreographer.java:731)
[ERROR] :  TiExceptionHandler:     android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
[ERROR] :  TiExceptionHandler:     android.os.Handler.handleCallback(Handler.java:938)
[ERROR] :  TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:99)
[ERROR] :  TiExceptionHandler:     android.os.Looper.loop(Looper.java:223)
[ERROR] :  TiExceptionHandler:     android.app.ActivityThread.main(ActivityThread.java:7656)
[ERROR] :  TiExceptionHandler:     java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiExceptionHandler:     com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[ERROR] :  TiExceptionHandler:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
-- End application log -------------------------------------------------------

**Comment by hansemannn** [comment]
You need the glide dependency, which you can get by using `av.imageview`

**Comment by moizchhatriwala** [comment]
I tried but nothing worked, even module doesn't compile and 3.0.0 module also doesn't worked for me, their may be some workaround needed to make this module workable. If I am able to do so I will definitely make the updated code available here.

**Comment by mawenlihk** [comment]
> You need the glide dependency, which you can get by using `av.imageview`

@hansemannn Thanks for providing this useful information! It really helps! Just a humble idea - would we consider reminding users about the necessity of this dependency in the project `README` file?

Also I'm wondering if there are still some extra configuration steps needed to make the _**Android**_ module 3.0.0 fully functional. Currently my project contains Titanium Android module `av.imageview` (version `5.0.2`). But when running my app on a real Android device, I can still see the following warnings in the console:

```
[WARN]  Glide: Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
[WARN]  Glide: Load failed for  with size [126x126]
[WARN]  Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
[WARN]  Glide:   Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{StringUri->Bitmap->Bitmap}, LOCAL
[WARN]  Glide:     Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Bitmap->Bitmap}
```

And I'm unable to see any photo in my phone as well.

**Comment by hansemannn** [comment]
The log is normal and not to worry about for now. To see the photos, you need to add proper runtime permission to read and write the external storage. After that, it should work.

**Comment by mawenlihk** [comment]
@hansemannn Thanks for the explanation 😃
